# Generated by Django 4.2.4 on 2023-09-02 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Начальная Широта геолокация врача')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Начальная Долгота геолокация врача')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта геолокация пациента')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота геолокация пациента')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('patient_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('doc_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_doctor.doctor', verbose_name='Назначен врач')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Текущая Широта геолокация врача')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Текущая Долгота геолокация врача')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_doctor.doctor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_doctor.orders')),
            ],
        ),
    ]
