# Generated by Django 4.2.4 on 2023-09-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Начальная Широта геолокация врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Начальная Долгота геолокация врача'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Широта геолокация пациента'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Долгота геолокация пациента'),
        ),
        migrations.AlterField(
            model_name='route',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Текущая Широта геолокация врача'),
        ),
        migrations.AlterField(
            model_name='route',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Текущая Долгота геолокация врача'),
        ),
    ]
