# Generated by Django 4.2.4 on 2023-09-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_doctor', '0003_alter_doctor_latitude_alter_doctor_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='doctor_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_doctor.route', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='route',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='По маршрута Широта геолокация врача'),
        ),
        migrations.AlterField(
            model_name='route',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='По маршруту Долгота геолокация врача'),
        ),
    ]
