# Generated by Django 4.2.4 on 2023-09-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_doctor', '0004_orders_doctor_route_alter_route_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='doctor_route',
        ),
    ]
